### PR TITLE
Update to 2.137.0 - added myself as maintainer

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@jan-janssen you added yourself as a maintainer without any commit message to that effect nor PR title.

**Comment by jan-janssen** [comment]
> @jan-janssen you added yourself as a maintainer without any commit message to that effect nor PR title.

I modified the title. The package was updated on pypi on the 9th of July, as the package name changed - `-` was replaced with `_` - the automated bot did not pick it up and it seems none of the current maintainers updated the recipe. So I stepped in and created the pull request to fix the package and added myself as maintainer to keep the package up to date in future as one of my own projects depends on it.

**Comment by akrherz** [comment]
I've got #199 going to take the package update part and can let others comment on the maintainer, but this look more like an upstream issue than conda-forge, see the previous release had the dashes in the file name,

> https://pypi.org/project/google-api-python-client/2.136.0/#files

**Comment by jan-janssen** [comment]
Thanks for fixing the issue - when you keep the feedstock up to date then there is no need to add me as the maintainer, I have far to many recipes already.

**Comment by akrherz** [comment]
reported upstream as googleapis/google-api-python-client#2437

**Comment by akrherz** [comment]
2.138.0 was just released and the pypi file continues to use underscores, so hopefully the bot picks things up cleanly in a little bit here.

**Pull request closed without merging**
